@startuml
(*) --> "获取PPT模板文件"
--> "分析PPT"
--> ===B1===
--> "确定图形的位置"
--> ===B2===

===B1=== --> "确定是否有特殊的需求"
--> ===B2===
--> "获取图表的数据"
--> "按照图形的位置构建数据"
--> "构建填充PPT图形"
--> "输出PPT文件"
--> (*)

@enduml